version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
      include: scope
    labels:
      - "type: chore"
      - "area: ci"
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
      include: scope
    labels:
      - "type: chore"
      - "area: ci"
    groups:
      npm:
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: /site
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
      include: scope
    labels:
      - "type: chore"
      - "area: ci"
    groups:
      site:
        patterns:
          - "*"
