/**
 * Public entry for the `okmodel` package.
 *
 * Builders, identity, and names live here. Catalog documents (serialisation,
 * parsing, hashing, and dependency order) stay in the catalog document module
 * so tooling does not enter this entry.
 */

export {
  CATALOG_CODES,
  COLUMN_CODES,
  ERROR_CATEGORIES,
  ERROR_KINDS,
  OkmError,
  catalogError,
  safe,
  throwNamed,
  type CatalogCode,
  type ColumnCode,
  type QueryCode,
  type ErrorCategory,
  type ErrorColumns,
  type ErrorFields,
  type ErrorFix,
  type ErrorKind,
  type ErrorLog,
  type ErrorStatuses,
  type HttpError,
  type HttpErrorBody,
  type OkmErrorOptions,
  type SafeResult,
} from "./error.js";
export { nearestName } from "./nearest.js";
export { sha256 } from "./sha256.js";
export type {
  AnySchema,
  AnyTableShape,
  Insert,
  Register,
  Row,
  SchemaOf,
  TableName,
  Update,
} from "./rows.js";

export {
  BUILT_KINDS,
  CATALOG_VERSION,
  KIND_OPERATIONS,
  OBJECT_KINDS,
  OBJECT_OPERATIONS,
  OWNERS,
  POSTGRES_IDENTIFIER_MAX_BYTES,
  assertIdentifier,
  assertNamespace,
  column,
  constraint,
  deterministicName,
  fitIdentifier,
  identityKey,
  identityLabel,
  identifierLimitApplies,
  index,
  isReservedIdentifier,
  resolveNamespace,
  sameNamespace,
  sameRef,
  sequence,
  staticNamespace,
  table,
  templateNamespace,
  utf8ByteLength,
  type AnchoredIdentity,
  type BuiltKind,
  type Catalog,
  type CatalogEnvelope,
  type CatalogObject,
  type ColumnDefinition,
  type ColumnInput,
  type ColumnObject,
  type ConstraintDefinition,
  type ConstraintInput,
  type ConstraintKind,
  type ConstraintObject,
  type DefaultPrivilegeIdentity,
  type DependencyEdge,
  type ExtensionIdentity,
  type FunctionIdentity,
  type GrantIdentity,
  type GrantObjectRef,
  type IndexDefinition,
  type IndexInput,
  type IndexObject,
  type NamePurpose,
  type Namespace,
  type NamespaceIdentity,
  type ObjectIdentity,
  type ObjectKind,
  type ObjectOperation,
  type ObjectRef,
  type Owner,
  type PartitionMethod,
  type Provenance,
  type ReferentialAction,
  type RoleIdentity,
  type SequenceDefinition,
  type SequenceInput,
  type SequenceObject,
  type TableDefinition,
  type TableInput,
  type TableObject,
} from "./catalog/index.js";

export type {
  DescribeResult,
  DriverCapabilities,
  DriverConnection,
  DriverErrorFields,
  DriverFailureKind,
  DriverPool,
  DriverPoolConfig,
  DriverStats,
  ExecuteOptions,
  ExecuteResult,
  Notice,
  PreparedMode,
  Statement,
  TransactionMode,
  WireValue,
} from "./driver.js";
