/**
 * Public entry for the `okmodel` package.
 *
 * The query API arrives in later prompts. The catalog and hashing live here
 * so later layers do not depend on a host crypto API.
 */

export { CATALOG_CODES, OkmError, catalogError, type CatalogCode } from "./error.js";
export { sha256 } from "./sha256.js";

export {
  BUILT_KINDS,
  CATALOG_VERSION,
  KIND_OPERATIONS,
  OBJECT_KINDS,
  OBJECT_OPERATIONS,
  OWNERS,
  POSTGRES_IDENTIFIER_MAX_BYTES,
  assertIdentifier,
  assertNamespace,
  catalog,
  catalogHash,
  column,
  constraint,
  creationOrder,
  dependencyOrder,
  deterministicName,
  fitIdentifier,
  identityKey,
  identityLabel,
  identifierLimitApplies,
  index,
  isReservedIdentifier,
  parseCatalog,
  renameColumn,
  resolveNamespace,
  sameNamespace,
  sameRef,
  sequence,
  serializeCatalog,
  staticNamespace,
  table,
  templateNamespace,
  utf8ByteLength,
  type AnchoredIdentity,
  type BuiltKind,
  type Catalog,
  type CatalogEnvelope,
  type CatalogObject,
  type ColumnDefinition,
  type ColumnInput,
  type ColumnObject,
  type ConstraintDefinition,
  type ConstraintInput,
  type ConstraintKind,
  type ConstraintObject,
  type DefaultPrivilegeIdentity,
  type DependencyEdge,
  type ExtensionIdentity,
  type FunctionIdentity,
  type GrantIdentity,
  type GrantObjectRef,
  type IndexDefinition,
  type IndexInput,
  type IndexObject,
  type NamePurpose,
  type Namespace,
  type NamespaceIdentity,
  type ObjectIdentity,
  type ObjectKind,
  type ObjectOperation,
  type ObjectRef,
  type Owner,
  type PartitionMethod,
  type Provenance,
  type RoleIdentity,
  type SequenceDefinition,
  type SequenceInput,
  type SequenceObject,
  type TableDefinition,
  type TableInput,
  type TableObject,
} from "./catalog/index.js";
