/**
 * Public entry for the `okmodel` package.
 *
 * Builders, identity, and names live here. Catalog documents (serialisation,
 * parsing, hashing, and dependency order) stay in the catalog document module
 * so tooling does not enter this entry.
 */

export {
  CATALOG_CODES,
  COLUMN_CODES,
  OkmError,
  catalogError,
  type CatalogCode,
  type ColumnCode,
} from "./error.js";
export { sha256 } from "./sha256.js";

export {
  BUILT_KINDS,
  CATALOG_VERSION,
  KIND_OPERATIONS,
  OBJECT_KINDS,
  OBJECT_OPERATIONS,
  OWNERS,
  POSTGRES_IDENTIFIER_MAX_BYTES,
  assertIdentifier,
  assertNamespace,
  column,
  constraint,
  deterministicName,
  fitIdentifier,
  identityKey,
  identityLabel,
  identifierLimitApplies,
  index,
  isReservedIdentifier,
  resolveNamespace,
  sameNamespace,
  sameRef,
  sequence,
  staticNamespace,
  table,
  templateNamespace,
  utf8ByteLength,
  type AnchoredIdentity,
  type BuiltKind,
  type Catalog,
  type CatalogEnvelope,
  type CatalogObject,
  type ColumnDefinition,
  type ColumnInput,
  type ColumnObject,
  type ConstraintDefinition,
  type ConstraintInput,
  type ConstraintKind,
  type ConstraintObject,
  type DefaultPrivilegeIdentity,
  type DependencyEdge,
  type ExtensionIdentity,
  type FunctionIdentity,
  type GrantIdentity,
  type GrantObjectRef,
  type IndexDefinition,
  type IndexInput,
  type IndexObject,
  type NamePurpose,
  type Namespace,
  type NamespaceIdentity,
  type ObjectIdentity,
  type ObjectKind,
  type ObjectOperation,
  type ObjectRef,
  type Owner,
  type PartitionMethod,
  type Provenance,
  type RoleIdentity,
  type SequenceDefinition,
  type SequenceInput,
  type SequenceObject,
  type TableDefinition,
  type TableInput,
  type TableObject,
} from "./catalog/index.js";
